name: assemblers
channels:
  - bioconda
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - _sysroot_linux-64_curr_repodata_hack=3=h5bd9786_13
  - bzip2=1.0.8=h7f98852_4
  - ca-certificates=2022.9.24=ha878542_0
  - kernel-headers_linux-64=3.10.0=h4a8ded7_13
  - ld_impl_linux-64=2.39=hc81fddc_0
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=12.2.0=h65d4601_18
  - libgomp=12.2.0=h65d4601_18
  - libnsl=2.0.0=h7f98852_0
  - libsqlite=3.39.4=h753d276_0
  - libstdcxx-ng=12.2.0=h46fd767_18
  - libuuid=2.32.1=h7f98852_1000
  - libzlib=1.2.13=h166bdaf_4
  - llvm-openmp=8.0.1=hc9558a2_0
  - megahit=1.2.9=h2e03b76_1
  - ncurses=6.3=h27087fc_1
  - openmp=8.0.1=0
  - openssl=3.0.5=h166bdaf_2
  - pip=22.3=pyhd8ed1ab_0
  - python=3.10.6=ha86cf86_0_cpython
  - readline=8.1.2=h0f457ee_0
  - setuptools=65.5.0=pyhd8ed1ab_0
  - spades=3.15.5=h95f258a_1
  - sysroot_linux-64=2.17=h4a8ded7_13
  - tk=8.6.12=h27826a3_0
  - tzdata=2022e=h191b570_0
  - wheel=0.37.1=pyhd8ed1ab_0
  - xz=5.2.6=h166bdaf_0
  - zlib=1.2.13=h166bdaf_4
